name: indoor-localization
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - matplotlib==3.9.2
      - numpy==2.1.2
      - pandas==2.2.3
      - requests==2.32.5
      - seaborn==0.13.2
      - xgboost==3.1.2
      - scikit-learn==1.5.2
      - torch==2.5.1+cu121
      - --extra-index-url https://download.pytorch.org/whl/cu121
